version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - PROCESSING_BUCKET=your-processing-bucket-name
    volumes:
      - ./backend:/app
      - ./google-credentials.json:/app/google-credentials.json:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://product-placement-pidup46kxa-nw.a.run.app